# Generated by Django 3.1.8 on 2021-11-08 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Insurance',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('debt', 'debt')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Referral_stage',
            field=models.CharField(blank=True, choices=[('stage1', 'stage1'), ('stage2', 'stage2'), ('stage3', 'stage3'), ('stage4', 'stage4')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='OTP_online_banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coinbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase_email', models.CharField(blank=True, max_length=200, null=True)),
                ('coinbase_password', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
