# Generated by Django 3.1.8 on 2021-12-06 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211108_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinbase',
            options={'verbose_name_plural': 'Coinbase'},
        ),
        migrations.AddField(
            model_name='client',
            name='payment_date',
            field=models.CharField(blank=True, choices=[('Not Due for Payment', 'Not Due for Payment'), (' Due for Payment', ' Due for Payment')], max_length=200),
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_email', models.CharField(blank=True, max_length=200, null=True)),
                ('crypto_password', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'crypto',
            },
        ),
    ]
