# Generated by Django 3.1.8 on 2022-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220310_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_profile',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
