# Generated by Django 3.1.8 on 2022-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221212_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='client/profile_pic/avatar.jpg', null=True, upload_to='client/profile_pic'),
        ),
    ]
