# Generated by Django 3.1.8 on 2023-01-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_withdrawal_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdrawal_Wallet',
            new_name='WithdrawalWallet',
        ),
        migrations.AlterModelOptions(
            name='withdrawalwallet',
            options={'verbose_name': 'Withdrawal Wallet'},
        ),
    ]
