# Generated by Django 3.1.8 on 2023-01-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230104_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_roi',
            new_name='roi_balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='total_roi_currency',
            new_name='roi_balance_currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='insurance_dept',
        ),
        migrations.RemoveField(
            model_name='account',
            name='no_of_investment',
        ),
        migrations.RemoveField(
            model_name='account',
            name='referral_dept',
        ),
    ]
