# Generated by Django 3.1.8 on 2023-01-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230107_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='expected_roi',
            new_name='roi_balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='expected_roi_currency',
            new_name='roi_balance_currency',
        ),
    ]
