# Generated by Django 3.1.8 on 2023-01-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230107_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_expected_roi',
            new_name='expected_roi',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='total_expected_roi_currency',
            new_name='expected_roi_currency',
        ),
    ]
