# Generated by Django 3.1.8 on 2023-01-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20230107_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='expected_roi',
            new_name='roi_bal',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='expected_roi_currency',
            new_name='roi_bal_currency',
        ),
    ]
