# Generated by Django 3.1.8 on 2023-01-07 11:45

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230107_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='roi_balance_currency',
            new_name='total_roi_currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roi_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='total_roi',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=19, null=True),
        ),
    ]
