# Generated by Django 3.1.8 on 2023-01-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230107_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='roi_bal',
            new_name='roi_balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='roi_bal_currency',
            new_name='roi_balance_currency',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='total_roi',
            new_name='total_expected_roi',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='total_roi_currency',
            new_name='total_expected_roi_currency',
        ),
    ]
