# Generated by Django 3.1.8 on 2023-08-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230107_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='id_back_view',
            new_name='id_view',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='city',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='country',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='id_front_view',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='state',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='zip',
        ),
    ]
