# Generated by Django 3.1.8 on 2022-03-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trx_code',
        ),
    ]
