# Generated by Django 3.1.8 on 2022-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_trx_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trx_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
