# Generated by Django 3.1.8 on 2022-03-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20220310_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trx_id',
            field=models.CharField(blank=True, default='NULL', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
