# Generated by Django 3.1.8 on 2022-12-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0001_initial'),
        ('transactions', '0009_auto_20221212_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boss.adminwallet'),
        ),
        migrations.DeleteModel(
            name='Payment_Method',
        ),
    ]
