# Generated by Django 3.1.8 on 2022-12-13 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0010_auto_20221213_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'Etherum'), ('USDT', 'USDT'), ('BNB', 'BNB'), ('XRP', 'XRP')], max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
