# Generated by Django 3.1.8 on 2022-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20221213_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BTC', 'BTC'), ('ETH', 'Etherum'), ('USDT', 'USDT'), ('BNB', 'BNB'), ('XRP', 'XRP')], max_length=200, null=True),
        ),
    ]
