# Generated by Django 3.1.8 on 2022-12-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
    ]
