# Generated by Django 3.1.8 on 2022-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20221215_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Investment'), (5, 'Transfer'), (6, 'ROI'), (4, 'Convert Bonus'), (7, 'Investment_Upgrade'), (8, 'Insurance Charge'), (9, 'Transfer Charge')], null=True),
        ),
    ]
