# Generated by Django 3.1.8 on 2023-01-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20221228_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Investment'), (5, 'Transfer'), (6, 'ROI'), (4, 'Convert Bonus'), (7, 'Investment_Upgrade'), (8, 'Convert ROI'), (9, 'Transfer Charge')], null=True),
        ),
    ]
