# Generated by Django 3.1.8 on 2023-01-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20230107_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expiry_date',
        ),
    ]
