# Generated by Django 3.1.8 on 2023-01-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_remove_transaction_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deposit_slip',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='investment_start_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='period_in_days',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='preferred_platform',
        ),
        migrations.DeleteModel(
            name='Customer_care',
        ),
        migrations.DeleteModel(
            name='Invest',
        ),
    ]
